name: angular_recaptcha
description: Google Angular Recaptcha
version: 0.0.10
homepage: https://github.com/lejard-h/angular_recaptcha
author: Hadrien Lejard <hadrien.lejard@gmail.com>
environment:
  sdk: ">=2.0.0-dev.46.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha
  angular_forms: ^2.0.0-alpha
  js: ^0.6.0
  dart_browser_loader: ^0.0.2

transformers:
  - angular