name: angular_recaptcha
description: Google Angular Recaptcha
version: 0.0.7
homepage: https://github.com/lejard-h/angular_recaptcha
author: Hadrien Lejard <hadrien.lejard@gmail.com>
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0-alpha
  js: ^0.6.0

transformers:
  - angular