name: angular_recaptcha
description: Google Angular Recaptcha
version: 0.0.2
homepage: https://github.com/lejard-h/angular_recaptcha
author: Hadrien Lejard <hadrien.lejard@gmail.com>
environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  angular2: ^2.2.0
  js: ^0.6.0
