name: angular_recaptcha
description: Google Angular Recaptcha
version: 0.1.5
homepage: https://github.com/lejard-h/angular_recaptcha

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  angular: ^7.0.0
  angular_forms: ^4.0.0
  js: ^0.6.3
  dart_browser_loader: ^0.0.6+1

dev_dependencies:
  pedantic: ^1.0.0
