name: angular_recaptcha
description: Google Angular Recaptcha
version: 0.0.9
homepage: https://github.com/lejard-h/angular_recaptcha
author: Hadrien Lejard <hadrien.lejard@gmail.com>
environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ">=4.0.0 <5.0.0"
  angular_forms: ^1.0.0
  js: ^0.6.0

transformers:
  - angular